# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#'
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: TTS
    url: tag/tts
    weight: 1
    parent: Publications
  - name: Voice Conversion
    url: tag/voice-conversion
    weight: 2
    parent: Publications
  - name: Talking Face
    url: tag/talking-face
    weight: 3
    parent: Publications
  - name: ASR
    url: tag/asr
    weight: 4
    parent: Publications
  - name: MIR
    url: tag/mir
    weight: 5
    parent: Publications
  - name: Speech
    url: tag/speech
    weight: 6
    parent: Publications
  - name: All
    url: publication
    weight: 7
    parent: Publications
  - name: Research
    url: research
    weight: 55
  - name: Pre-Avatar
    url: pre-avatar
    weight: 60
  - name: Contact
    url: contact
    weight: 70



